[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts = -v --tb=auto --durations=10 --color=yes --showlocals --no-header --log-level=DEBUG
