"""public api schema

Revision ID: 22b899e90ca7
Revises: c4c8f1f89fdf
Create Date: 2026-06-29 09:47:28.257089+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "22b899e90ca7"
down_revision: Union[str, Sequence[str], None] = "c4c8f1f89fdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_categories",
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=120), nullable=False),
        sa.Column("description", sa.VARCHAR(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name="fk_product_categories_tenant_id_organizations",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_product_categories_tenant_slug"),
    )
    op.create_index(op.f("ix_product_categories_id"), "product_categories", ["id"], unique=False)
    op.create_index(
        op.f("ix_product_categories_slug"), "product_categories", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_product_categories_tenant_id"), "product_categories", ["tenant_id"], unique=False
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("webhook_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name="fk_webhook_deliveries_tenant_id_organizations",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
            name="fk_webhook_deliveries_webhook_id_webhooks",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_event_type"), "webhook_deliveries", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_webhook_deliveries_id"), "webhook_deliveries", ["id"], unique=False)
    op.create_index(
        op.f("ix_webhook_deliveries_tenant_id"), "webhook_deliveries", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False
    )
    op.create_table(
        "external_topup_sessions",
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("card_id", sa.UUID(), nullable=True),
        sa.Column("wallet_id", sa.UUID(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.VARCHAR(length=3), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("external_payment_ref", sa.VARCHAR(length=200), nullable=True),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name="fk_external_topup_sessions_card_id_cards",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name="fk_external_topup_sessions_customer_id_customers",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name="fk_external_topup_sessions_tenant_id_organizations",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name="fk_external_topup_sessions_transaction_id_transactions",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
            name="fk_external_topup_sessions_wallet_id_wallets",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_external_topup_sessions_tenant_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_external_topup_sessions_card_id"),
        "external_topup_sessions",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_topup_sessions_customer_id"),
        "external_topup_sessions",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_topup_sessions_external_payment_ref"),
        "external_topup_sessions",
        ["external_payment_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_topup_sessions_id"), "external_topup_sessions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_external_topup_sessions_idempotency_key"),
        "external_topup_sessions",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_topup_sessions_tenant_id"),
        "external_topup_sessions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_topup_sessions_transaction_id"),
        "external_topup_sessions",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_topup_sessions_wallet_id"),
        "external_topup_sessions",
        ["wallet_id"],
        unique=False,
    )
    op.add_column("products", sa.Column("category_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_foreign_key(
        "fk_products_category_id_product_categories",
        "products",
        "product_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_products_category_id_product_categories", "products", type_="foreignkey")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_column("products", "category_id")
    op.drop_index(
        op.f("ix_external_topup_sessions_wallet_id"), table_name="external_topup_sessions"
    )
    op.drop_index(
        op.f("ix_external_topup_sessions_transaction_id"), table_name="external_topup_sessions"
    )
    op.drop_index(
        op.f("ix_external_topup_sessions_tenant_id"), table_name="external_topup_sessions"
    )
    op.drop_index(
        op.f("ix_external_topup_sessions_idempotency_key"), table_name="external_topup_sessions"
    )
    op.drop_index(op.f("ix_external_topup_sessions_id"), table_name="external_topup_sessions")
    op.drop_index(
        op.f("ix_external_topup_sessions_external_payment_ref"),
        table_name="external_topup_sessions",
    )
    op.drop_index(
        op.f("ix_external_topup_sessions_customer_id"), table_name="external_topup_sessions"
    )
    op.drop_index(op.f("ix_external_topup_sessions_card_id"), table_name="external_topup_sessions")
    op.drop_table("external_topup_sessions")
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_tenant_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_event_type"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_product_categories_tenant_id"), table_name="product_categories")
    op.drop_index(op.f("ix_product_categories_slug"), table_name="product_categories")
    op.drop_index(op.f("ix_product_categories_id"), table_name="product_categories")
    op.drop_table("product_categories")
    # ### end Alembic commands ###
