"""device api schema

Revision ID: c4c8f1f89fdf
Revises: 5c8ff5569db9
Create Date: 2026-06-29 09:14:16.008020+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c4c8f1f89fdf'
down_revision: Union[str, Sequence[str], None] = '5c8ff5569db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmwares',
    sa.Column('version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('target_device_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('binary_url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_firmwares_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmwares_id'), 'firmwares', ['id'], unique=False)
    op.create_index(op.f('ix_firmwares_tenant_id'), 'firmwares', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_firmwares_version'), 'firmwares', ['version'], unique=False)
    op.create_table('payment_methods',
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_payment_methods_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_payment_methods_tenant_code')
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_payment_methods_tenant_id'), 'payment_methods', ['tenant_id'], unique=False)
    op.create_table('device_commands',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_device_commands_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_device_commands_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_commands_device_id'), 'device_commands', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_commands_id'), 'device_commands', ['id'], unique=False)
    op.create_index(op.f('ix_device_commands_tenant_id'), 'device_commands', ['tenant_id'], unique=False)
    op.create_table('device_heartbeats',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_device_heartbeats_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_device_heartbeats_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_heartbeats_device_id'), 'device_heartbeats', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeats_id'), 'device_heartbeats', ['id'], unique=False)
    op.create_index(op.f('ix_device_heartbeats_tenant_id'), 'device_heartbeats', ['tenant_id'], unique=False)
    op.create_table('device_telemetry',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('uptime_s', sa.BigInteger(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_device_telemetry_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_device_telemetry_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_telemetry_device_id'), 'device_telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_telemetry_id'), 'device_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_device_telemetry_tenant_id'), 'device_telemetry', ['tenant_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_device_tokens_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_device_tokens_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_device_id'), 'device_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_tenant_id'), 'device_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_token_hash'), 'device_tokens', ['token_hash'], unique=True)
    op.create_table('firmware_updates',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('firmware_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_firmware_updates_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firmware_id'], ['firmwares.id'], name='fk_firmware_updates_firmware_id_firmwares', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_firmware_updates_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_updates_device_id'), 'firmware_updates', ['device_id'], unique=False)
    op.create_index(op.f('ix_firmware_updates_firmware_id'), 'firmware_updates', ['firmware_id'], unique=False)
    op.create_index(op.f('ix_firmware_updates_id'), 'firmware_updates', ['id'], unique=False)
    op.create_index(op.f('ix_firmware_updates_tenant_id'), 'firmware_updates', ['tenant_id'], unique=False)
    op.create_table('temp_card_assignments',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('session_ref', sa.VARCHAR(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='fk_temp_card_assignments_card_id_cards', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_temp_card_assignments_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_card_assignments_card_id'), 'temp_card_assignments', ['card_id'], unique=False)
    op.create_index(op.f('ix_temp_card_assignments_id'), 'temp_card_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_temp_card_assignments_session_ref'), 'temp_card_assignments', ['session_ref'], unique=False)
    op.create_index(op.f('ix_temp_card_assignments_tenant_id'), 'temp_card_assignments', ['tenant_id'], unique=False)
    op.create_table('holds',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capture_transaction_id'], ['transactions.id'], name='fk_holds_capture_transaction_id_transactions', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='fk_holds_card_id_cards', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_holds_device_id_devices', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_holds_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='fk_holds_wallet_id_wallets', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_holds_tenant_idempotency_key')
    )
    op.create_index(op.f('ix_holds_capture_transaction_id'), 'holds', ['capture_transaction_id'], unique=False)
    op.create_index(op.f('ix_holds_card_id'), 'holds', ['card_id'], unique=False)
    op.create_index(op.f('ix_holds_device_id'), 'holds', ['device_id'], unique=False)
    op.create_index(op.f('ix_holds_id'), 'holds', ['id'], unique=False)
    op.create_index(op.f('ix_holds_idempotency_key'), 'holds', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_holds_tenant_id'), 'holds', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_holds_wallet_id'), 'holds', ['wallet_id'], unique=False)
    op.create_table('kiosk_topup_sessions',
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_kiosk_topup_sessions_customer_id_customers', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], name='fk_kiosk_topup_sessions_kiosk_id_kiosks', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_kiosk_topup_sessions_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_kiosk_topup_sessions_transaction_id_transactions', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_kiosk_topup_sessions_tenant_idempotency_key')
    )
    op.create_index(op.f('ix_kiosk_topup_sessions_customer_id'), 'kiosk_topup_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_kiosk_topup_sessions_id'), 'kiosk_topup_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_kiosk_topup_sessions_idempotency_key'), 'kiosk_topup_sessions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_kiosk_topup_sessions_kiosk_id'), 'kiosk_topup_sessions', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_kiosk_topup_sessions_tenant_id'), 'kiosk_topup_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kiosk_topup_sessions_transaction_id'), 'kiosk_topup_sessions', ['transaction_id'], unique=False)
    op.create_table('offline_transactions',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('applied_transaction_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_transaction_id'], ['transactions.id'], name='fk_offline_transactions_applied_transaction_id_transactions', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_offline_transactions_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_offline_transactions_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_offline_transactions_tenant_idempotency_key')
    )
    op.create_index(op.f('ix_offline_transactions_applied_transaction_id'), 'offline_transactions', ['applied_transaction_id'], unique=False)
    op.create_index(op.f('ix_offline_transactions_device_id'), 'offline_transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_offline_transactions_id'), 'offline_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_offline_transactions_idempotency_key'), 'offline_transactions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_offline_transactions_tenant_id'), 'offline_transactions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offline_transactions_tenant_id'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_idempotency_key'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_id'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_device_id'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_applied_transaction_id'), table_name='offline_transactions')
    op.drop_table('offline_transactions')
    op.drop_index(op.f('ix_kiosk_topup_sessions_transaction_id'), table_name='kiosk_topup_sessions')
    op.drop_index(op.f('ix_kiosk_topup_sessions_tenant_id'), table_name='kiosk_topup_sessions')
    op.drop_index(op.f('ix_kiosk_topup_sessions_kiosk_id'), table_name='kiosk_topup_sessions')
    op.drop_index(op.f('ix_kiosk_topup_sessions_idempotency_key'), table_name='kiosk_topup_sessions')
    op.drop_index(op.f('ix_kiosk_topup_sessions_id'), table_name='kiosk_topup_sessions')
    op.drop_index(op.f('ix_kiosk_topup_sessions_customer_id'), table_name='kiosk_topup_sessions')
    op.drop_table('kiosk_topup_sessions')
    op.drop_index(op.f('ix_holds_wallet_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_tenant_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_idempotency_key'), table_name='holds')
    op.drop_index(op.f('ix_holds_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_device_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_card_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_capture_transaction_id'), table_name='holds')
    op.drop_table('holds')
    op.drop_index(op.f('ix_temp_card_assignments_tenant_id'), table_name='temp_card_assignments')
    op.drop_index(op.f('ix_temp_card_assignments_session_ref'), table_name='temp_card_assignments')
    op.drop_index(op.f('ix_temp_card_assignments_id'), table_name='temp_card_assignments')
    op.drop_index(op.f('ix_temp_card_assignments_card_id'), table_name='temp_card_assignments')
    op.drop_table('temp_card_assignments')
    op.drop_index(op.f('ix_firmware_updates_tenant_id'), table_name='firmware_updates')
    op.drop_index(op.f('ix_firmware_updates_id'), table_name='firmware_updates')
    op.drop_index(op.f('ix_firmware_updates_firmware_id'), table_name='firmware_updates')
    op.drop_index(op.f('ix_firmware_updates_device_id'), table_name='firmware_updates')
    op.drop_table('firmware_updates')
    op.drop_index(op.f('ix_device_tokens_token_hash'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_tenant_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_device_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_device_telemetry_tenant_id'), table_name='device_telemetry')
    op.drop_index(op.f('ix_device_telemetry_id'), table_name='device_telemetry')
    op.drop_index(op.f('ix_device_telemetry_device_id'), table_name='device_telemetry')
    op.drop_table('device_telemetry')
    op.drop_index(op.f('ix_device_heartbeats_tenant_id'), table_name='device_heartbeats')
    op.drop_index(op.f('ix_device_heartbeats_id'), table_name='device_heartbeats')
    op.drop_index(op.f('ix_device_heartbeats_device_id'), table_name='device_heartbeats')
    op.drop_table('device_heartbeats')
    op.drop_index(op.f('ix_device_commands_tenant_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_device_id'), table_name='device_commands')
    op.drop_table('device_commands')
    op.drop_index(op.f('ix_payment_methods_tenant_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_firmwares_version'), table_name='firmwares')
    op.drop_index(op.f('ix_firmwares_tenant_id'), table_name='firmwares')
    op.drop_index(op.f('ix_firmwares_id'), table_name='firmwares')
    op.drop_table('firmwares')
    # ### end Alembic commands ###
