"""admin api initial schema

Revision ID: 5c8ff5569db9
Revises: 
Create Date: 2026-06-29 03:31:07.420045+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5c8ff5569db9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('default_currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('permissions',
    sa.Column('code', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('billing_settings',
    sa.Column('plan', sa.VARCHAR(length=50), nullable=False),
    sa.Column('billing_email', sa.VARCHAR(length=320), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('payment_method', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_billing_settings_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_settings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customers',
    sa.Column('external_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_customers_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id', name='uq_customers_tenant_external_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('locations',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_locations_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('org_settings',
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_org_settings_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_settings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission_id_permissions', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_permissions_role_id_roles', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('security_settings',
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('password_policy', sa.JSON(), nullable=True),
    sa.Column('ip_allowlist', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_security_settings_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_settings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role_id_roles', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_users_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_webhooks_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhooks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=16), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_api_keys_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_api_keys_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=120), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name='fk_audit_logs_actor_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_audit_logs_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cards',
    sa.Column('uid', sa.VARCHAR(length=120), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_cards_customer_id_customers', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_cards_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'uid', name='uq_cards_tenant_uid')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_uid'), ['uid'], unique=False)

    op.create_table('devices',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('serial', sa.VARCHAR(length=120), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_devices_location_id_locations', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_devices_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kiosks',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_kiosks_location_id_locations', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_kiosks_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosks_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_memberships_role_id_roles', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_memberships_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_memberships_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_notifications_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=120), nullable=False),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_products_location_id_locations', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_products_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_products_tenant_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_tokens_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('wallets',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_wallets_customer_id_customers', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_wallets_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('device_configs',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_device_configs_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_device_configs_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_configs_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_configs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('device_events',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_device_events_device_id_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_device_events_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kiosk_logs',
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], name='fk_kiosk_logs_kiosk_id_kiosks', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_kiosk_logs_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_logs_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('transactions',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_transactions_customer_id_customers', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='fk_transactions_device_id_devices', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_transactions_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='fk_transactions_wallet_id_wallets', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_transactions_tenant_idempotency_key')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_ledger_entries_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_ledger_entries_transaction_id_transactions', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='fk_ledger_entries_wallet_id_wallets', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('refunds',
    sa.Column('original_transaction_id', sa.UUID(), nullable=False),
    sa.Column('refund_transaction_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['transactions.id'], name='fk_refunds_original_transaction_id_transactions', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_transaction_id'], ['transactions.id'], name='fk_refunds_refund_transaction_id_transactions', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_refunds_tenant_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_original_transaction_id'), ['original_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_refund_transaction_id'), ['refund_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('wallet_transfers',
    sa.Column('from_wallet_id', sa.UUID(), nullable=False),
    sa.Column('to_wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], name='fk_wallet_transfers_from_wallet_id_wallets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name='fk_wallet_transfers_tenant_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], name='fk_wallet_transfers_to_wallet_id_wallets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_wallet_transfers_transaction_id_transactions', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transfers_from_wallet_id'), ['from_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transfers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transfers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transfers_to_wallet_id'), ['to_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transfers_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transfers_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transfers_to_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transfers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transfers_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transfers_from_wallet_id'))

    op.drop_table('wallet_transfers')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_refund_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_original_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_device_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('kiosk_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_logs_kiosk_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_logs_id'))

    op.drop_table('kiosk_logs')
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_device_events_id'))
        batch_op.drop_index(batch_op.f('ix_device_events_device_id'))

    op.drop_table('device_events')
    with op.batch_alter_table('device_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_device_configs_id'))
        batch_op.drop_index(batch_op.f('ix_device_configs_device_id'))

    op.drop_table('device_configs')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_customer_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_location_id'))
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_role_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('kiosks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_kiosks_location_id'))
        batch_op.drop_index(batch_op.f('ix_kiosks_id'))

    op.drop_table('kiosks')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_devices_serial'))
        batch_op.drop_index(batch_op.f('ix_devices_location_id'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_uid'))
        batch_op.drop_index(batch_op.f('ix_cards_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cards_id'))
        batch_op.drop_index(batch_op.f('ix_cards_customer_id'))

    op.drop_table('cards')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_webhooks_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_settings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_security_settings_id'))

    op.drop_table('security_settings')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('org_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_settings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_org_settings_id'))

    op.drop_table('org_settings')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_external_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    with op.batch_alter_table('billing_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_settings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_settings_id'))

    op.drop_table('billing_settings')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
